#!/usr/bin/env python

"""A simple script that sleeps for the specified duration, and ignores all other arguments"""

import argparse
import time

def parse_args():
    # yapf: disable
    parser = argparse.ArgumentParser(description='',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('duration', type=float)
    args, _ = parser.parse_known_args()
    return args

if __name__ == "__main__":
    args = parse_args()
    time.sleep(args.duration)
